### ISSUE TITLE
Do we support create meeting Room through rtc JS SDK ?

### ISSUE THREAD

**Issue by TD-tenglong** [infobip/infobip-rtc-js#1]
Hi, dear team.

Do we support create meeting Room through rtc JS SDK ?
Thanks

**Comment by adnanel** [comment]
Hi,

If you are talking about room calls - rooms are automatically created when the first person joins, using the [joinRoom](https://github.com/infobip/infobip-rtc-js/wiki/InfobipRTC#join-room) method, and are destroyed when the last person leaves.

However, please don't confuse rooms with conferences. Those are created using [Calls API](https://www.infobip.com/docs/api/channels/voice/calls/conference-calls/create-conference).

**Comment by TD-tenglong** [comment]
Right, we need to create a video/voice room to allow no more than three people to join in.  Such as **call-link**, user could join the meeting with video and voice.

With the room calls and conferences, Which one do you think is better for our scenarios ? 

BTW, we noticed that the doc mentioned [here](https://github.com/infobip/infobip-rtc-js/wiki/Room-calls-migration-guide). If we understand right, we should use Room calls.

Thanks

**Comment by adnanel** [comment]
Do you want to limit the number of users in call-link, or in conferences/rooms?

Rooms don't support defining such restrictions, so you would have to use conferences.

You would have to use [callApplication](https://github.com/infobip/infobip-rtc-js/wiki/InfobipRTC#call-application) which would use your application as described in our [docs](https://www.infobip.com/docs/voice-and-video/calls#applications-concepts).

Once you have your application setup, you can call that application using the mentioned SDK method. Then you can do with that call whatever you want, i.e. you can define a custom logic such as joining them into a conference with custom restrictions as defined by you.
 
Of course this assumes that you are building your own application and not using our [call link solution](https://www.infobip.com/video/call-link), which has these things sorted out for you, so you don't have to implement anything.

**Comment by TD-tenglong** [comment]
We will consider the restrictions in the **future**, but now we only consider **two** or **three** people in a Meeting Room.

Actually, we have used the **call-link** for our demo, which is perfect👌. For commercial usage, we will purchase the WebRTC services, and we have to create a similar Web App as well. Our customers could use our URL and UI styles. 😁

Our Scenario: 
1. Our agent will generate a link just like what Call-link does. Then send it to the contact person.
2. Agent and contact person will join this meeting room.
3. Using video/audio, and share screen functionalities.

Thanks for your docs, What if we use the RoomCall apis? Any restrictions or limitations compare with the [callApplication](https://github.com/infobip/infobip-rtc-js/wiki/InfobipRTC#call-application) ?

BTW, I do research on the docs and call-link. Does your team have some other demos or open source GitHub repos to share ? We may appreciate it. 

Thanks

**Comment by adnanel** [comment]
Any reason why you are trying to recreate Call Link, considering there is no additional fee for using Call Link over WebRTC?
If you feel something is missing in Call Link you might request that feature if that's your only blocker.

In any case, rooms are for basic use cases where you want to allows users to join a room without any restrictions. This is going to be your biggest limitation to deal with. 

callApplication is going to give you the maximum flexibility, i.e. you will have to have your own backend which will serve as the business logic defining who joins which call/conference.

There are some very basic showcases which show the concept:
- https://github.com/infobip/infobip-calls-showcase
  - This is an example backend application which handles incoming calls
- https://github.com/infobip/infobip-rtc-showcase
  - This is a repository which contains several showcases. Here you can see the frontend which uses callApplication, and the corresponding backend implementations.

**Comment by TD-tenglong** [comment]
Thanks for your showcases, really appreciate.

> In any case, rooms are for basic use cases where you want to allows users to join a room without any restrictions. This is going to be your biggest limitation to deal with.
> 
You are right, the room is for basic use cases(video/audio/share screen), our clients have to use these basic functionalities to connect with their potential customers, whom **DO NOT NEED** to request any authorization to join in (Both sides will join from a shared link). So the restrictions will not be considered now.

> Any reason why you are trying to recreate Call Link, considering there is no additional fee for using Call Link over WebRTC? If you feel something is missing in Call Link you might request that feature if that's your only blocker.
> 
The call-link use the https://call-link.com/{ID}, we should use our domain name instead of it, and the UI styles are different with ours. 😁
BTW, Which APIs does call-link use if there are two people join a meeting for basic uses? 

> callApplication is going to give you the maximum flexibility, i.e. you will have to have your own backend which will serve as the business logic defining who joins which call/conference.
> 
We do not have a plan to implement a backend service, due to our limitation of usage. Just for basic use cases. 😊

**Comment by adnanel** [comment]
Call links are generated using [the Create Call Link API](https://www.infobip.com/docs/api/channels/webrtc-calls/call-link/create-call-link). 

Take a look at the destination field, they support both ROOM for basic use cases, but also APPLICATION in case you want to use the call link customizable web frontend in combination with your backend to handle the call. Depending on the destination, they decide which SDK method to use.

**Comment by TD-tenglong** [comment]
Thanks for your explanation, really appreciate.

We will use the basic Room call methods to show our integrations with your WebRTC services at present.

**Comment by littlbee** [comment]
Hello,
just quickly chiming in. Please note that for Call Link you can request subdomains, such as "mysubdomain.call-link.com". We plan to support full domain onboarding later this year.
I get your comment about the UI style. If you wish, we can open that discussion in a separate thread and see if there is any adaptation we could add on Call Link that would suit your needs.

**Comment by TD-tenglong** [comment]
@littlbee Thanks for your reply.

We're currently working on a single independent web application which will integrate the Room Call APis from Infobip this month.  

After the demo show in the early April this year, we will consider the usage of the Call Link, But the domain name and the UI styles are really important for ours product, If the full domain and UI styles matched our requirement, I would be happy to suggest our team to fully migrate to Call Link.

> Hello, just quickly chiming in. Please note that for Call Link you can request subdomains, such as "mysubdomain.call-link.com". We plan to support full domain onboarding later this year. I get your comment about the UI style. If you wish, we can open that discussion in a separate thread and see if there is any adaptation we could add on Call Link that would suit your needs.
>
For the UI style, If we could discuss it, I'm happy to. But we have to deliver the demo show first.

**Comment by littlbee** [comment]
OK, understood @TD-tenglong . I'll reach out on LinkedIn to connect, from there we can see based on your project timing when it would be best to plan a meeting together.
