### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by TD-tenglong** [infobip/infobip-rtc-js#2]
Hi, there, Could you please tell me , the meaning of this error msg, Maybe miss configuring my applicaiton:
Received message from Infobip Gateway: {"event":"hangup","callId":"345d1800-c193-4135-90b7-593c1e7bfb08","status":{"id":10300,"name":"FORBIDDEN","description":"The received request was rejected."}}.

Thanks

**Comment by adnanel** [comment]
This is related to your trial plan. I was told someone already reached out to you & your account manager so I assume this is sorted out. In case you have new questions feel free to reopen or open a new ticket.

**Comment by TD-tenglong** [comment]
Thanks
