### ISSUE TITLE
When I call the leave method to leave the Room, I want to turn the camera off. What should I do

### ISSUE THREAD

**Issue by qianjunhu** [infobip/infobip-rtc-js#4]
When I joined a RoomCall video chat, I actively called the leave method to leave the room, but there was a problem, the camera was not turned off, what should I do? Do I need to turn off all streams manually? Also clean up the elements of the video receiving the stream? Does the sdk provide packaged methods?

https://github.com/user-attachments/assets/6b1c9be3-af67-4ea0-873f-48925a4f30f9
![image](https://github.com/user-attachments/assets/3ed0648e-6dd1-4850-b199-a1e69f3d48ea)

**Comment by adnanel** [comment]
Hi, usually that should happen automatically, albeit with a small delay since it happens asynchronously.

What SDK version are you using?
Are there any errors in your dev console? Please include the call ID where this happens.

Thanks

**Comment by qianjunhu** [comment]
> Hi, usually that should happen automatically, albeit with a small delay since it happens asynchronously.
> 
> What SDK version are you using? Are there any errors in your dev console? Please include the call ID where this happens.
> 
> Thanks

I re-tested it with the information you provided and yes both the camera and microphone turn off automatically after a period of time, thank you very much!

**Comment by qianjunhu** [comment]
Also I have another question for you, when I use `setAudioInputDevice(deviceId)` and `setVideoInputDevice(deviceId)` to set the device, can I still use these two api to switch the device when I enter Room call?
![image](https://github.com/user-attachments/assets/b809c8d5-8808-4797-b02d-963c3a14ce93)

**Comment by adnanel** [comment]
How long do you have to wait? This shouldn't take more than a few moments.

The setters on `InfobipRTC` are for setting device defaults. To change the device while in a call, use:

https://github.com/infobip/infobip-rtc-js/wiki/Call#set-audio-input-device

**Comment by qianjunhu** [comment]
Yes, it shuts down after a few seconds, so can I switch devices after joining Room? Or can I only set up the device after connecting to rtc?

**Comment by adnanel** [comment]
You can do both.

Before joining the room (app config), use:
https://github.com/infobip/infobip-rtc-js/wiki/InfobipRTC#set-audio-input-device
https://github.com/infobip/infobip-rtc-js/wiki/InfobipRTC#set-video-input-device

After joining the room (call UI), use:
https://github.com/infobip/infobip-rtc-js/wiki/Call#set-audio-input-device

I see now that the setVideoInputDevice is missing in the docs, but it also exists on the call object, we will document it soon.

**Comment by qianjunhu** [comment]
Thanks
