### ISSUE TITLE
 Maximum communication time

### ISSUE THREAD

**Issue by qianjunhu** [infobip/infobip-rtc-js#6]
Hi, if we join the room via CallLink mode, will there be a maximum communication time limit for the conference? Or will the conference continue without interruption as long as there are people in the room?

**Comment by adnanel** [comment]
Hey, super sorry for the late response. Regarding the max duration, for calls it is currently 8 hours.

**Comment by qianjunhu** [comment]
@adnanel  I'm sorry to see your reply until now, but I have another question, Do we have configuration items for this maximum audio and video time custom configuration?

**Comment by qianjunhu** [comment]
@adnanel  We have another scenario, when there is only one participant left in the room, will there be a maximum time limit, or do we need to implement this feature ourselves?
